### PR TITLE
Skip empty inputs

### PR DESCRIPTION
**Pull request by zeppelin**
Validations triggered on change events would do their work prematurely.

@simonihmig I'm not sure how to write an acceptance test for this :/

### CODE REVIEW

**Comment by simonihmig** [comment]
@zeppelin Makes sense, thanks!

> I'm not sure how to write an acceptance test for this

Hm, not sure. Maybe test that no change event gets triggered. But I would accept this PR also without a test, but only this time! ;)

Tests are failing due to unrelated changes in Travis. To fix this for now and get this PR green, can you please add another `'--no-sandbox'` option here: https://github.com/kaliber5/ember-fastboot-form-rehydration/blob/master/testem.js#L18

**Comment by zeppelin** [comment]
@simonihmig That part is clear :) What makes me wonder is *when* to attach the listeners, as there is no clear way to do this in acceptance tests (AFAIK).

**Comment by simonihmig** [comment]
Re: testing, my first thought about this would be to add an action (on change) to some input in the dummy app, that creates a noticeable side effect, like adding a `changed` class. Which presence then can be asserted in the test (or rather its non-presence). So not dealing with listeners in the test itself. Does that make sense?

This would even allow to test that we *are* triggering a `change` event (for non-empty inputs), which we do not cover in tests yet AFAIR.

**Comment by zeppelin** [comment]
@simonihmig Didn't think of that, thanks - added tests as well! I was thinking too much in test case isolation...

**Review by simonihmig — APPROVED** [review]
Awesome, thanks!

**Comment by simonihmig** [comment]
Released as 0.1.3!

**Comment by zeppelin** [comment]
Thank you! :)

**Pull request merged**
