### PR TITLE
Don't try to restore focus on non-existent inputs

### PR DESCRIPTION
**Pull request by zeppelin**
Essentially the same check that happens [here](https://github.com/kaliber5/ember-fastboot-form-rehydration/blob/master/addon/services/form-rehydration.js#L49), for the focused input.

### CODE REVIEW

**Review by simonihmig — APPROVED** [review]

**Comment by simonihmig** [comment]
Thanks @zeppelin, this looks good! But the tests are all failing, because some version of `sane` is requiring node 6+. Some package seems to have dropped node 4 support without a major version bump. 😔

Anyway, we should do the same, either update the node version ind `package.json` and `travis.yml`, or do a full `ember-cli-update` run, and release as 0.2.0. Would you be able to do that? I am pretty short on time this and the next week at least...

**Comment by zeppelin** [comment]
Turns out an unrelated test somehow fails :/

Will investigate...

**Comment by zeppelin** [comment]
@simonihmig I can't seem to get this working. It's all fine locally in every browser, but fails on CI.

**Comment by zeppelin** [comment]
I think it's safe to close this now 😅

**Pull request closed without merging**
